config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :events do
    resources :comments
  end

  resources :events
  devise_for :users
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'

  root :to => 'events#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base

	has_many :comments, :dependent => :destroy
	belongs_to :user
	has_attached_file :image, styles: { medium: "320x240>" }
	

	validates :title, presence: true
	validates :user_id, presence: true
	validates_attachment :image, presence: true, 
					content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
					size: { less_than: 5.megabytes }
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
         :rememberable, :trackable, :validatable

  has_many :events
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create(comment_params)
    @comment.user = current_user
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @event, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id, :event_id)
  end

  # PUT /comments/1
  # PUT /comments/1.json
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order("created_at desc")
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = current_user.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<p>
		<% unless comment.user.nil? %>
			<%= comment.user.name %> says:
		<% end %>
		<strong><%= h(comment.body) %></strong></br>
		Posted <%= time_ago_in_words(comment.created_at) %> ago
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :pin_id %>

    <%= f.input :body %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Pin</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.pin_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pin:</strong>
  <%= @comment.pin_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/events/_event.html.erb
<div class="col-lg-4 col-md-6">
	<div class="well">
		<h3><%= event.title %></h3><br><br>
		<%= link_to (image_tag event.image(:medium)), event, class: "img-responsive"%><br><br>
		<%= event.description %><br><br>
		created by <%= event.user.name %>
		<br><br>
		<%= link_to 'Show', event, class: "btn btn-success" %>
		<% if current_user == event.user %>
		<%= link_to 'Edit', edit_event_path(event), class: "btn btn-primary" %>
		<%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
		<% end %>
	</div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-danger" %>
  <%= f.full_error :image_content_type, class: "alert alert-danger" %>

  <div class="form-inputs">

    <%= f.input :title %>

    <%= f.input :description, as: :text, input_html: {rows: "3"} %>

    <%= f.input :image, label: "Upload a cover" %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @event, class: "btn btn-primary" %> |
<%= link_to 'Back', events_path, class: "btn btn-primary" %>

app/views/events/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= render 'pages/home' %>

<h1>Events</h1>
<div class="container">
  <div class="row">
<%= render @events %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', events_path, class: "btn btn-primary" %>

app/views/events/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="container">
<div class="row">
	<div class="col-lg-6">
		<div class="well">
			<%= image_tag @event.image(:medium) %>
			<p>
				<strong>Title:</strong>
				<%= @event.title %>
			</p>

			<p>
				<strong>Description:</strong>
				<%= @event.description %>
			</p>

			<p>
				<strong>Created by:</strong>
				<%= @event.user.name %>
			</p>


		<% if current_user == @event.user %>
		<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-primary" %> |
		<% end %>
		<%= link_to 'Back', events_path, class: "btn btn-primary" %>
		<H4>Comments</H4>
				<div id="comments">
					<%= render :partial => @event.comments %>
				</div>
				<%= simple_form_for [@event, Comment.new] do |f| %>
				<p>
					<!--<%= f.label :body, "New Comment" %></br>
					<%= f.text_area :body %> -->
					<%= f.input :body, :label => "New Comment", as: :text, input_html: { rows: "3" } %>
				</p>
				<p><%= f.submit "Add Comment", class: "btn btn-primary" %></p>
		<% end %>	

				</div>
	</div>
	<div class="col-lg-6"></div>
</div>
</div>

app/views/layouts/_footer.html.erb

<div class="footer">
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-63095183-1', 'auto');
		ga('send', 'pageview');

	</script>
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<small>
		by CodeLight Studios
	</small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Echo</a> -->
      <%= link_to "Echo", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
        <li><%= link_to "Add New Event", new_event_path %></li>
        <li><%= link_to "Welcome " + current_user.name.to_s , edit_user_registration_path %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Echo</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header'%>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-warning") %>
		<% end %>
		<%= yield %>	
		<%= render 'layouts/footer'%>
	</div>
	
</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>
<!-- <div class="jumbotron">
	<h1>Echo</h1>
	<p>Find your interests and dive deep to interact.</p>
</div> -->
<% else %>
<div class="jumbotron">
	<h1>Echo</h1>
	<p>
		Welcome to a new world of sharing your views with the people.
		<%= link_to "Coming soon", "#"%>
	</p>

	<p><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn-large"%>
	</p>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>I am Kalyan Dechiraju from CodeLight Studios</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<div class="jumbotron">
	<h1>Echo</h1>
	<p>You are now logged in</p>
</div>
<% else %>
<div class="jumbotron">
	<h1>Echo</h1>
	<p>
		Welcome to a new world of sharing your views with the people.
		<%= link_to "Coming soon", "#"%>
	</p>

	<p><%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn-large"%>
	</p>
</div>
<% end %>